DROP TABLE IF EXISTS emailqueue;
CREATE TABLE emailqueue (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	person_id INTEGER NOT NULL,
	filename VARCHAR(15) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
